/*******************************************************************************
 *                                                                             *
 * This file is generated by BitFontCreator Pro v3.8                           *
 * by Iseatech Software   http://www.iseasoft.com/bitfontcreator.html          *
 *                        support@iseasoft.com                                 *
 *                                                                             *
 * Font name: Arial                                                            *
 * Font width: 0 (proportional font)                                           *
 * Font height: 13                                                             *
 * Encode: Unicode                                                             *
 * Data length: 8 bits                                                         *
 * Invert bits: No                                                             *
 * Data format: Little Endian, Row based, Row preferred, Packed                *
 *                                                                             *
 * Create time: 15:36 10-02-2022                                               *
 *******************************************************************************/

#include <stdio.h>
#include "bfctype.h" 

/*  The following line needs to be included in any file selecting the
    font.
*/
extern const FONTHEADER_BFC fontArial10_B;

#define USE_OFFSET_TABLE
#define USE_WIDTH_TABLE
#define USE_ASCII_INDEX_TABLE
#define USE_EXTENDED_INDEX_TABLE


/*******************************************************************************************
  Data table provides the bitmap data of each character.

  To get the starting data offset of character 'A', you can use the following expression:

     const USHORT index = GetExtendedIndex('A');
     const ULONG offset = offset_table[index];
     const UCHAR *pData = &data_table[offset];

 *******************************************************************************************/
const UCHAR fontArial10_B_data_table[] = 
{
    /*character 0x0020 (' '): [width=4, offset= 0x0000 (0) ]*/
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 

    /*character 0x0021 ('!'): [width=4, offset= 0x0007 (7) ]*/
    0x66, 0x66, 0x66, 0x06, 0x66, 0x00, 0x00, 

    /*character 0x0022 ('"'): [width=6, offset= 0x000E (14) ]*/
    0xB6, 0x6D, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 

    /*character 0x0023 ('#'): [width=7, offset= 0x0018 (24) ]*/
    0x24, 0x12, 0xE9, 0x27, 0x91, 0xFC, 0x12, 0x89, 0x04, 0x00, 0x00, 0x00, 

    /*character 0x0024 ('$'): [width=7, offset= 0x0024 (36) ]*/
    0x1C, 0x95, 0xC2, 0xE1, 0xE1, 0xE1, 0x50, 0x2A, 0x0E, 0x02, 0x00, 0x00, 

    /*character 0x0025 ('%'): [width=10, offset= 0x0030 (48) ]*/
    0x4E, 0x28, 0xA1, 0x84, 0x0A, 0x2E, 0x40, 0x07, 0x15, 0x54, 0x48, 0x21, 0x07, 0x00, 0x00, 0x00, 
    0x00, 

    /*character 0x0026 ('&'): [width=9, offset= 0x0041 (65) ]*/
    0x38, 0xD8, 0xB0, 0xC1, 0x83, 0x81, 0x97, 0x2D, 0x73, 0xE6, 0x78, 0x03, 0x00, 0x00, 0x00, 

    /*character 0x0027 ('''): [width=3, offset= 0x0050 (80) ]*/
    0xB6, 0x01, 0x00, 0x00, 0x00, 

    /*character 0x0028 ('('): [width=4, offset= 0x0055 (85) ]*/
    0xC8, 0x64, 0x66, 0x66, 0x66, 0xC4, 0x08, 

    /*character 0x0029 (')'): [width=4, offset= 0x005C (92) ]*/
    0x31, 0x62, 0x66, 0x66, 0x66, 0x32, 0x01, 

    /*character 0x002A ('*'): [width=5, offset= 0x0063 (99) ]*/
    0xE4, 0x93, 0x0D, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 

    /*character 0x002B ('+'): [width=8, offset= 0x006C (108) ]*/
    0x00, 0x00, 0x00, 0x18, 0x18, 0x7E, 0x18, 0x18, 0x00, 0x00, 0x00, 0x00, 0x00, 

    /*character 0x002C (','): [width=4, offset= 0x0079 (121) ]*/
    0x00, 0x00, 0x00, 0x00, 0x66, 0x24, 0x00, 

    /*character 0x002D ('-'): [width=4, offset= 0x0080 (128) ]*/
    0x00, 0x00, 0x00, 0xE0, 0x00, 0x00, 0x00, 

    /*character 0x002E ('.'): [width=4, offset= 0x0087 (135) ]*/
    0x00, 0x00, 0x00, 0x00, 0x66, 0x00, 0x00, 

    /*character 0x002F ('/'): [width=4, offset= 0x008E (142) ]*/
    0x88, 0x44, 0x24, 0x22, 0x11, 0x00, 0x00, 

    /*character 0x0030 ('0'): [width=7, offset= 0x0095 (149) ]*/
    0x9E, 0xD9, 0x6C, 0x36, 0x9B, 0xCD, 0x66, 0x33, 0x0F, 0x00, 0x00, 0x00, 

    /*character 0x0031 ('1'): [width=7, offset= 0x00A1 (161) ]*/
    0x18, 0x8E, 0x47, 0x83, 0xC1, 0x60, 0x30, 0x18, 0x0C, 0x00, 0x00, 0x00, 

    /*character 0x0032 ('2'): [width=7, offset= 0x00AD (173) ]*/
    0x9E, 0x19, 0x0C, 0x86, 0xE1, 0x30, 0x0C, 0x83, 0x1F, 0x00, 0x00, 0x00, 

    /*character 0x0033 ('3'): [width=7, offset= 0x00B9 (185) ]*/
    0x9E, 0x19, 0x0C, 0xC6, 0x81, 0xC1, 0x60, 0x33, 0x0F, 0x00, 0x00, 0x00, 

    /*character 0x0034 ('4'): [width=7, offset= 0x00C5 (197) ]*/
    0x18, 0x0C, 0x87, 0xA3, 0xD1, 0x64, 0x7E, 0x18, 0x0C, 0x00, 0x00, 0x00, 

    /*character 0x0035 ('5'): [width=7, offset= 0x00D1 (209) ]*/
    0x3E, 0xC3, 0xE0, 0x33, 0x83, 0xC1, 0x60, 0x33, 0x0F, 0x00, 0x00, 0x00, 

    /*character 0x0036 ('6'): [width=7, offset= 0x00DD (221) ]*/
    0x1C, 0xD9, 0x60, 0xF0, 0x99, 0xCD, 0x66, 0x33, 0x0F, 0x00, 0x00, 0x00, 

    /*character 0x0037 ('7'): [width=7, offset= 0x00E9 (233) ]*/
    0x3F, 0x18, 0x06, 0xC3, 0x60, 0x30, 0x0C, 0x06, 0x03, 0x00, 0x00, 0x00, 

    /*character 0x0038 ('8'): [width=7, offset= 0x00F5 (245) ]*/
    0x9E, 0xD9, 0x6C, 0xE6, 0x99, 0xCD, 0x66, 0x33, 0x0F, 0x00, 0x00, 0x00, 

    /*character 0x0039 ('9'): [width=7, offset= 0x0101 (257) ]*/
    0x9E, 0xD9, 0x6C, 0x36, 0xF3, 0xC1, 0x60, 0x13, 0x07, 0x00, 0x00, 0x00, 

    /*character 0x003A (':'): [width=4, offset= 0x010D (269) ]*/
    0x00, 0x60, 0x06, 0x00, 0x66, 0x00, 0x00, 

    /*character 0x003B (';'): [width=4, offset= 0x0114 (276) ]*/
    0x00, 0x60, 0x06, 0x00, 0x66, 0x24, 0x00, 

    /*character 0x003C ('<'): [width=8, offset= 0x011B (283) ]*/
    0x00, 0x00, 0x20, 0x38, 0x0E, 0x03, 0x0E, 0x38, 0x20, 0x00, 0x00, 0x00, 0x00, 

    /*character 0x003D ('='): [width=8, offset= 0x0128 (296) ]*/
    0x00, 0x00, 0x00, 0x00, 0x7F, 0x00, 0x7F, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 

    /*character 0x003E ('>'): [width=8, offset= 0x0135 (309) ]*/
    0x00, 0x00, 0x02, 0x0E, 0x38, 0x60, 0x38, 0x0E, 0x02, 0x00, 0x00, 0x00, 0x00, 

    /*character 0x003F ('?'): [width=8, offset= 0x0142 (322) ]*/
    0x3E, 0x63, 0x60, 0x60, 0x30, 0x18, 0x0C, 0x00, 0x0C, 0x0C, 0x00, 0x00, 0x00, 

    /*character 0x0040 ('@'): [width=13, offset= 0x014F (335) ]*/
    0xF0, 0x83, 0x81, 0x18, 0x20, 0xB9, 0x99, 0x3F, 0x3B, 0x67, 0x63, 0x6C, 0x4E, 0xFD, 0x4D, 0x77, 
    0x08, 0x40, 0x06, 0x06, 0x3F, 0x00, 

    /*character 0x0041 ('A'): [width=9, offset= 0x0165 (357) ]*/
    0x38, 0x70, 0xB0, 0x61, 0xC3, 0xC6, 0x98, 0x31, 0x7F, 0x83, 0x07, 0x03, 0x00, 0x00, 0x00, 

    /*character 0x0042 ('B'): [width=9, offset= 0x0174 (372) ]*/
    0x7E, 0x8C, 0x19, 0x33, 0xE6, 0xC7, 0x98, 0x31, 0x63, 0xC6, 0xFC, 0x00, 0x00, 0x00, 0x00, 

    /*character 0x0043 ('C'): [width=9, offset= 0x0183 (387) ]*/
    0xF8, 0x18, 0x1B, 0x30, 0x60, 0xC0, 0x80, 0x01, 0x03, 0x8C, 0xF1, 0x01, 0x00, 0x00, 0x00, 

    /*character 0x0044 ('D'): [width=9, offset= 0x0192 (402) ]*/
    0x3E, 0xCC, 0x18, 0x33, 0x66, 0xCC, 0x98, 0x31, 0x63, 0x66, 0x7C, 0x00, 0x00, 0x00, 0x00, 

    /*character 0x0045 ('E'): [width=8, offset= 0x01A1 (417) ]*/
    0x7E, 0x06, 0x06, 0x06, 0x7E, 0x06, 0x06, 0x06, 0x06, 0x7E, 0x00, 0x00, 0x00, 

    /*character 0x0046 ('F'): [width=8, offset= 0x01AE (430) ]*/
    0x7E, 0x06, 0x06, 0x06, 0x06, 0x7E, 0x06, 0x06, 0x06, 0x06, 0x00, 0x00, 0x00, 

    /*character 0x0047 ('G'): [width=10, offset= 0x01BB (443) ]*/
    0xF8, 0x30, 0x66, 0x80, 0x01, 0x06, 0x98, 0x67, 0x98, 0x61, 0x8C, 0xE1, 0x03, 0x00, 0x00, 0x00, 
    0x00, 

    /*character 0x0048 ('H'): [width=9, offset= 0x01CC (460) ]*/
    0xC6, 0x8C, 0x19, 0x33, 0xE6, 0xCF, 0x98, 0x31, 0x63, 0xC6, 0x8C, 0x01, 0x00, 0x00, 0x00, 

    /*character 0x0049 ('I'): [width=4, offset= 0x01DB (475) ]*/
    0x66, 0x66, 0x66, 0x66, 0x66, 0x00, 0x00, 

    /*character 0x004A ('J'): [width=7, offset= 0x01E2 (482) ]*/
    0x30, 0x18, 0x0C, 0x06, 0x83, 0xC1, 0x66, 0x33, 0x0F, 0x00, 0x00, 0x00, 

    /*character 0x004B ('K'): [width=9, offset= 0x01EE (494) ]*/
    0xC6, 0xCC, 0xD8, 0xB0, 0xE1, 0xC3, 0x8D, 0x19, 0x33, 0xC6, 0x8C, 0x01, 0x00, 0x00, 0x00, 

    /*character 0x004C ('L'): [width=8, offset= 0x01FD (509) ]*/
    0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x7E, 0x00, 0x00, 0x00, 

    /*character 0x004D ('M'): [width=11, offset= 0x020A (522) ]*/
    0x8E, 0x73, 0x9C, 0xF7, 0xBC, 0x67, 0x35, 0xAB, 0x59, 0xCD, 0x6E, 0x76, 0x33, 0x19, 0x00, 0x00, 
    0x00, 0x00, 

    /*character 0x004E ('N'): [width=9, offset= 0x021C (540) ]*/
    0xC6, 0x9C, 0x39, 0xF3, 0x66, 0xCD, 0x9E, 0x39, 0x73, 0xC6, 0x8C, 0x01, 0x00, 0x00, 0x00, 

    /*character 0x004F ('O'): [width=10, offset= 0x022B (555) ]*/
    0x78, 0x30, 0x63, 0x98, 0x61, 0x86, 0x19, 0x66, 0x98, 0x61, 0xCC, 0xE0, 0x01, 0x00, 0x00, 0x00, 
    0x00, 

    /*character 0x0050 ('P'): [width=9, offset= 0x023C (572) ]*/
    0x7E, 0x8C, 0x19, 0x33, 0x66, 0xCC, 0x8F, 0x01, 0x03, 0x06, 0x0C, 0x00, 0x00, 0x00, 0x00, 

    /*character 0x0051 ('Q'): [width=10, offset= 0x024B (587) ]*/
    0x78, 0x30, 0x63, 0x98, 0x61, 0x86, 0x19, 0x66, 0x98, 0x69, 0xCC, 0xE0, 0x03, 0x10, 0x00, 0x00, 
    0x00, 

    /*character 0x0052 ('R'): [width=9, offset= 0x025C (604) ]*/
    0x7E, 0x8C, 0x19, 0x33, 0x66, 0xCC, 0x8F, 0x19, 0x63, 0xC6, 0x0C, 0x03, 0x00, 0x00, 0x00, 

    /*character 0x0053 ('S'): [width=9, offset= 0x026B (619) ]*/
    0x7C, 0x8C, 0x19, 0x70, 0xC0, 0x03, 0x0F, 0x38, 0x60, 0xC6, 0xF8, 0x00, 0x00, 0x00, 0x00, 

    /*character 0x0054 ('T'): [width=8, offset= 0x027A (634) ]*/
    0xFF, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x00, 0x00, 0x00, 

    /*character 0x0055 ('U'): [width=9, offset= 0x0287 (647) ]*/
    0xC6, 0x8C, 0x19, 0x33, 0x66, 0xCC, 0x98, 0x31, 0x63, 0xC6, 0xF8, 0x00, 0x00, 0x00, 0x00, 

    /*character 0x0056 ('V'): [width=9, offset= 0x0296 (662) ]*/
    0x83, 0x07, 0x1B, 0x33, 0x66, 0x8C, 0x0D, 0x1B, 0x36, 0x38, 0x70, 0x00, 0x00, 0x00, 0x00, 

    /*character 0x0057 ('W'): [width=13, offset= 0x02A5 (677) ]*/
    0xE3, 0x78, 0x1C, 0x9B, 0x33, 0xDB, 0x66, 0xDB, 0x6C, 0x9B, 0x6D, 0xE3, 0x38, 0x1C, 0x87, 0xE3, 
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 

    /*character 0x0058 ('X'): [width=9, offset= 0x02BB (699) ]*/
    0xC6, 0x8C, 0xB1, 0xC1, 0x81, 0x03, 0x07, 0x0E, 0x36, 0xC6, 0x8C, 0x01, 0x00, 0x00, 0x00, 

    /*character 0x0059 ('Y'): [width=10, offset= 0x02CA (714) ]*/
    0x86, 0x19, 0xC6, 0x0C, 0x1E, 0x78, 0xC0, 0x00, 0x03, 0x0C, 0x30, 0xC0, 0x00, 0x00, 0x00, 0x00, 
    0x00, 

    /*character 0x005A ('Z'): [width=7, offset= 0x02DB (731) ]*/
    0x7F, 0x30, 0x0C, 0x83, 0x61, 0x30, 0x0C, 0x83, 0x3F, 0x00, 0x00, 0x00, 

    /*character 0x005B ('['): [width=4, offset= 0x02E7 (743) ]*/
    0x6E, 0x66, 0x66, 0x66, 0x66, 0x66, 0x0E, 

    /*character 0x005C ('\'): [width=4, offset= 0x02EE (750) ]*/
    0x11, 0x22, 0x42, 0x44, 0x88, 0x00, 0x00, 

    /*character 0x005D (']'): [width=4, offset= 0x02F5 (757) ]*/
    0x67, 0x66, 0x66, 0x66, 0x66, 0x66, 0x07, 

    /*character 0x005E ('^'): [width=8, offset= 0x02FC (764) ]*/
    0x00, 0x0C, 0x0C, 0x1E, 0x12, 0x33, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 

    /*character 0x005F ('_'): [width=7, offset= 0x0309 (777) ]*/
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xF0, 0x07, 

    /*character 0x0060 ('`'): [width=4, offset= 0x0315 (789) ]*/
    0x63, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 

    /*character 0x0061 ('a'): [width=8, offset= 0x031C (796) ]*/
    0x00, 0x00, 0x00, 0x3C, 0x62, 0x78, 0x6C, 0x66, 0x66, 0x7C, 0x00, 0x00, 0x00, 

    /*character 0x0062 ('b'): [width=8, offset= 0x0329 (809) ]*/
    0x06, 0x06, 0x06, 0x36, 0x6E, 0x66, 0x66, 0x66, 0x6E, 0x36, 0x00, 0x00, 0x00, 

    /*character 0x0063 ('c'): [width=7, offset= 0x0336 (822) ]*/
    0x00, 0x00, 0x80, 0x67, 0x36, 0x18, 0x0C, 0x66, 0x1E, 0x00, 0x00, 0x00, 

    /*character 0x0064 ('d'): [width=8, offset= 0x0342 (834) ]*/
    0x60, 0x60, 0x60, 0x6C, 0x76, 0x66, 0x66, 0x66, 0x76, 0x6C, 0x00, 0x00, 0x00, 

    /*character 0x0065 ('e'): [width=8, offset= 0x034F (847) ]*/
    0x00, 0x00, 0x00, 0x3C, 0x66, 0x66, 0x7E, 0x06, 0x66, 0x3C, 0x00, 0x00, 0x00, 

    /*character 0x0066 ('f'): [width=5, offset= 0x035C (860) ]*/
    0xDC, 0x98, 0x67, 0x8C, 0x31, 0xC6, 0x00, 0x00, 0x00, 

    /*character 0x0067 ('g'): [width=8, offset= 0x0365 (869) ]*/
    0x00, 0x00, 0x00, 0x6C, 0x76, 0x66, 0x66, 0x66, 0x76, 0x6C, 0x60, 0x62, 0x3C, 

    /*character 0x0068 ('h'): [width=8, offset= 0x0372 (882) ]*/
    0x06, 0x06, 0x06, 0x36, 0x6E, 0x66, 0x66, 0x66, 0x66, 0x66, 0x00, 0x00, 0x00, 

    /*character 0x0069 ('i'): [width=4, offset= 0x037F (895) ]*/
    0x66, 0x60, 0x66, 0x66, 0x66, 0x00, 0x00, 

    /*character 0x006A ('j'): [width=4, offset= 0x0386 (902) ]*/
    0xCC, 0xC0, 0xCC, 0xCC, 0xCC, 0xCC, 0x07, 

    /*character 0x006B ('k'): [width=7, offset= 0x038D (909) ]*/
    0x06, 0x83, 0xC1, 0x6C, 0xF3, 0x78, 0x6C, 0x36, 0x33, 0x00, 0x00, 0x00, 

    /*character 0x006C ('l'): [width=4, offset= 0x0399 (921) ]*/
    0x66, 0x66, 0x66, 0x66, 0x66, 0x00, 0x00, 

    /*character 0x006D ('m'): [width=12, offset= 0x03A0 (928) ]*/
    0x00, 0x00, 0x00, 0x00, 0x60, 0x37, 0xEE, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x00, 
    0x00, 0x00, 0x00, 0x00, 

    /*character 0x006E ('n'): [width=8, offset= 0x03B4 (948) ]*/
    0x00, 0x00, 0x00, 0x36, 0x6E, 0x66, 0x66, 0x66, 0x66, 0x66, 0x00, 0x00, 0x00, 

    /*character 0x006F ('o'): [width=8, offset= 0x03C1 (961) ]*/
    0x00, 0x00, 0x00, 0x3C, 0x66, 0x66, 0x66, 0x66, 0x66, 0x3C, 0x00, 0x00, 0x00, 

    /*character 0x0070 ('p'): [width=8, offset= 0x03CE (974) ]*/
    0x00, 0x00, 0x00, 0x36, 0x6E, 0x66, 0x66, 0x66, 0x6E, 0x36, 0x06, 0x06, 0x06, 

    /*character 0x0071 ('q'): [width=8, offset= 0x03DB (987) ]*/
    0x00, 0x00, 0x00, 0x6C, 0x76, 0x66, 0x66, 0x66, 0x76, 0x6C, 0x60, 0x60, 0x60, 

    /*character 0x0072 ('r'): [width=5, offset= 0x03E8 (1000) ]*/
    0x00, 0x00, 0x6F, 0x8C, 0x31, 0xC6, 0x00, 0x00, 0x00, 

    /*character 0x0073 ('s'): [width=6, offset= 0x03F1 (1009) ]*/
    0x00, 0x00, 0x78, 0xF3, 0xE1, 0xE1, 0xB3, 0x07, 0x00, 0x00, 

    /*character 0x0074 ('t'): [width=4, offset= 0x03FB (1019) ]*/
    0x40, 0xF6, 0x66, 0x66, 0xC6, 0x00, 0x00, 

    /*character 0x0075 ('u'): [width=8, offset= 0x0402 (1026) ]*/
    0x00, 0x00, 0x00, 0x66, 0x66, 0x66, 0x66, 0x66, 0x76, 0x6C, 0x00, 0x00, 0x00, 

    /*character 0x0076 ('v'): [width=9, offset= 0x040F (1039) ]*/
    0x00, 0x00, 0x00, 0x30, 0x66, 0x8C, 0x0D, 0x1B, 0x36, 0x38, 0x70, 0x00, 0x00, 0x00, 0x00, 

    /*character 0x0077 ('w'): [width=11, offset= 0x041E (1054) ]*/
    0x00, 0x00, 0x00, 0x00, 0x46, 0x3C, 0x67, 0xBB, 0x59, 0xCD, 0x7B, 0xDC, 0x61, 0x0C, 0x00, 0x00, 
    0x00, 0x00, 

    /*character 0x0078 ('x'): [width=8, offset= 0x0430 (1072) ]*/
    0x00, 0x00, 0x00, 0x66, 0x66, 0x3C, 0x18, 0x3C, 0x66, 0x66, 0x00, 0x00, 0x00, 

    /*character 0x0079 ('y'): [width=7, offset= 0x043D (1085) ]*/
    0x00, 0x00, 0x60, 0x3C, 0xB6, 0xD9, 0x6C, 0x1C, 0x0E, 0x87, 0xF1, 0x00, 

    /*character 0x007A ('z'): [width=7, offset= 0x0449 (1097) ]*/
    0x00, 0x00, 0xC0, 0x07, 0xC3, 0x30, 0x18, 0x06, 0x1F, 0x00, 0x00, 0x00, 

    /*character 0x007B ('{'): [width=5, offset= 0x0455 (1109) ]*/
    0xDC, 0x18, 0x63, 0xCC, 0x30, 0xC6, 0x18, 0xC3, 0x01, 

    /*character 0x007C ('|'): [width=3, offset= 0x045E (1118) ]*/
    0x92, 0x24, 0x49, 0x92, 0x04, 

    /*character 0x007D ('}'): [width=5, offset= 0x0463 (1123) ]*/
    0x87, 0x31, 0xC6, 0x18, 0x66, 0x8C, 0x31, 0x76, 0x00
};


#ifdef USE_OFFSET_TABLE
/*******************************************************************************************
  Offset table provides the starting offset of each character in the data table.

  If you can calculate the offsets by yourself, undefine USE_OFFSET_TABLE.

  To get the starting offset of character 'A', you can use the following expression:

     const USHORT index = GetExtendedIndex('A');
     const ULONG offset = offset_table[index];

 *******************************************************************************************/
const ULONG fontArial10_B_offset_table[] = 
{
    /*            -  char     hexcode    decimal */
    /*            -  ====     =======    ======= */
    0x0000, /*    -              0020         32 */
    0x0007, /*    -     !        0021         33 */
    0x000E, /*    -     "        0022         34 */
    0x0018, /*    -     #        0023         35 */
    0x0024, /*    -     $        0024         36 */
    0x0030, /*    -     %        0025         37 */
    0x0041, /*    -     &        0026         38 */
    0x0050, /*    -     '        0027         39 */
    0x0055, /*    -     (        0028         40 */
    0x005C, /*    -     )        0029         41 */
    0x0063, /*    -     *        002A         42 */
    0x006C, /*    -     +        002B         43 */
    0x0079, /*    -     ,        002C         44 */
    0x0080, /*    -     -        002D         45 */
    0x0087, /*    -     .        002E         46 */
    0x008E, /*    -     /        002F         47 */
    0x0095, /*    -     0        0030         48 */
    0x00A1, /*    -     1        0031         49 */
    0x00AD, /*    -     2        0032         50 */
    0x00B9, /*    -     3        0033         51 */
    0x00C5, /*    -     4        0034         52 */
    0x00D1, /*    -     5        0035         53 */
    0x00DD, /*    -     6        0036         54 */
    0x00E9, /*    -     7        0037         55 */
    0x00F5, /*    -     8        0038         56 */
    0x0101, /*    -     9        0039         57 */
    0x010D, /*    -     :        003A         58 */
    0x0114, /*    -     ;        003B         59 */
    0x011B, /*    -     <        003C         60 */
    0x0128, /*    -     =        003D         61 */
    0x0135, /*    -     >        003E         62 */
    0x0142, /*    -     ?        003F         63 */
    0x014F, /*    -     @        0040         64 */
    0x0165, /*    -     A        0041         65 */
    0x0174, /*    -     B        0042         66 */
    0x0183, /*    -     C        0043         67 */
    0x0192, /*    -     D        0044         68 */
    0x01A1, /*    -     E        0045         69 */
    0x01AE, /*    -     F        0046         70 */
    0x01BB, /*    -     G        0047         71 */
    0x01CC, /*    -     H        0048         72 */
    0x01DB, /*    -     I        0049         73 */
    0x01E2, /*    -     J        004A         74 */
    0x01EE, /*    -     K        004B         75 */
    0x01FD, /*    -     L        004C         76 */
    0x020A, /*    -     M        004D         77 */
    0x021C, /*    -     N        004E         78 */
    0x022B, /*    -     O        004F         79 */
    0x023C, /*    -     P        0050         80 */
    0x024B, /*    -     Q        0051         81 */
    0x025C, /*    -     R        0052         82 */
    0x026B, /*    -     S        0053         83 */
    0x027A, /*    -     T        0054         84 */
    0x0287, /*    -     U        0055         85 */
    0x0296, /*    -     V        0056         86 */
    0x02A5, /*    -     W        0057         87 */
    0x02BB, /*    -     X        0058         88 */
    0x02CA, /*    -     Y        0059         89 */
    0x02DB, /*    -     Z        005A         90 */
    0x02E7, /*    -     [        005B         91 */
    0x02EE, /*    -     \        005C         92 */
    0x02F5, /*    -     ]        005D         93 */
    0x02FC, /*    -     ^        005E         94 */
    0x0309, /*    -     _        005F         95 */
    0x0315, /*    -     `        0060         96 */
    0x031C, /*    -     a        0061         97 */
    0x0329, /*    -     b        0062         98 */
    0x0336, /*    -     c        0063         99 */
    0x0342, /*    -     d        0064        100 */
    0x034F, /*    -     e        0065        101 */
    0x035C, /*    -     f        0066        102 */
    0x0365, /*    -     g        0067        103 */
    0x0372, /*    -     h        0068        104 */
    0x037F, /*    -     i        0069        105 */
    0x0386, /*    -     j        006A        106 */
    0x038D, /*    -     k        006B        107 */
    0x0399, /*    -     l        006C        108 */
    0x03A0, /*    -     m        006D        109 */
    0x03B4, /*    -     n        006E        110 */
    0x03C1, /*    -     o        006F        111 */
    0x03CE, /*    -     p        0070        112 */
    0x03DB, /*    -     q        0071        113 */
    0x03E8, /*    -     r        0072        114 */
    0x03F1, /*    -     s        0073        115 */
    0x03FB, /*    -     t        0074        116 */
    0x0402, /*    -     u        0075        117 */
    0x040F, /*    -     v        0076        118 */
    0x041E, /*    -     w        0077        119 */
    0x0430, /*    -     x        0078        120 */
    0x043D, /*    -     y        0079        121 */
    0x0449, /*    -     z        007A        122 */
    0x0455, /*    -     {        007B        123 */
    0x045E, /*    -     |        007C        124 */
    0x0463, /*    -     }        007D        125 */
    0x046C  /*    -  extra address: the end of the last character's imagebits data. */
};
#endif


#ifdef USE_WIDTH_TABLE
/*******************************************************************************************
  Width table provides the width of each character. It's useful for proportional font.
  For monospaced font, the widths of all character are the same.

  Generally speaking, the width table is not needed for monospaced font. you can get
  the width from the font header.

  If you do not need the width table, undefine USE_WIDTH_TABLE.

  To get the width of character 'A', you can use the following expression:

     const USHORT index = GetExtendedIndex('A');
     const USHORT width = width_table[index];

 *******************************************************************************************/
const USHORT fontArial10_B_width_table[] = 
{
    /*      -  char     hexcode    decimal */
    /*      -  ====     =======    ======= */
     4,     /*             0020         32 */
     4,     /*    !        0021         33 */
     6,     /*    "        0022         34 */
     7,     /*    #        0023         35 */
     7,     /*    $        0024         36 */
    10,     /*    %        0025         37 */
     9,     /*    &        0026         38 */
     3,     /*    '        0027         39 */
     4,     /*    (        0028         40 */
     4,     /*    )        0029         41 */
     5,     /*    *        002A         42 */
     8,     /*    +        002B         43 */
     4,     /*    ,        002C         44 */
     4,     /*    -        002D         45 */
     4,     /*    .        002E         46 */
     4,     /*    /        002F         47 */
     7,     /*    0        0030         48 */
     7,     /*    1        0031         49 */
     7,     /*    2        0032         50 */
     7,     /*    3        0033         51 */
     7,     /*    4        0034         52 */
     7,     /*    5        0035         53 */
     7,     /*    6        0036         54 */
     7,     /*    7        0037         55 */
     7,     /*    8        0038         56 */
     7,     /*    9        0039         57 */
     4,     /*    :        003A         58 */
     4,     /*    ;        003B         59 */
     8,     /*    <        003C         60 */
     8,     /*    =        003D         61 */
     8,     /*    >        003E         62 */
     8,     /*    ?        003F         63 */
    13,     /*    @        0040         64 */
     9,     /*    A        0041         65 */
     9,     /*    B        0042         66 */
     9,     /*    C        0043         67 */
     9,     /*    D        0044         68 */
     8,     /*    E        0045         69 */
     8,     /*    F        0046         70 */
    10,     /*    G        0047         71 */
     9,     /*    H        0048         72 */
     4,     /*    I        0049         73 */
     7,     /*    J        004A         74 */
     9,     /*    K        004B         75 */
     8,     /*    L        004C         76 */
    11,     /*    M        004D         77 */
     9,     /*    N        004E         78 */
    10,     /*    O        004F         79 */
     9,     /*    P        0050         80 */
    10,     /*    Q        0051         81 */
     9,     /*    R        0052         82 */
     9,     /*    S        0053         83 */
     8,     /*    T        0054         84 */
     9,     /*    U        0055         85 */
     9,     /*    V        0056         86 */
    13,     /*    W        0057         87 */
     9,     /*    X        0058         88 */
    10,     /*    Y        0059         89 */
     7,     /*    Z        005A         90 */
     4,     /*    [        005B         91 */
     4,     /*    \        005C         92 */
     4,     /*    ]        005D         93 */
     8,     /*    ^        005E         94 */
     7,     /*    _        005F         95 */
     4,     /*    `        0060         96 */
     8,     /*    a        0061         97 */
     8,     /*    b        0062         98 */
     7,     /*    c        0063         99 */
     8,     /*    d        0064        100 */
     8,     /*    e        0065        101 */
     5,     /*    f        0066        102 */
     8,     /*    g        0067        103 */
     8,     /*    h        0068        104 */
     4,     /*    i        0069        105 */
     4,     /*    j        006A        106 */
     7,     /*    k        006B        107 */
     4,     /*    l        006C        108 */
    12,     /*    m        006D        109 */
     8,     /*    n        006E        110 */
     8,     /*    o        006F        111 */
     8,     /*    p        0070        112 */
     8,     /*    q        0071        113 */
     5,     /*    r        0072        114 */
     6,     /*    s        0073        115 */
     4,     /*    t        0074        116 */
     8,     /*    u        0075        117 */
     9,     /*    v        0076        118 */
    11,     /*    w        0077        119 */
     8,     /*    x        0078        120 */
     7,     /*    y        0079        121 */
     7,     /*    z        007A        122 */
     5,     /*    {        007B        123 */
     3,     /*    |        007C        124 */
     5      /*    }        007D        125 */
};
#endif


#ifdef USE_ASCII_INDEX_TABLE
/*******************************************************************************************
  Ascii index table is used to find the mapping index of a character in range [0-255].

  If you can find a simple mathematical expression for index mapping, you can use that.
  If you do not have such a mathematical expression, this index table is just for you.

  To get the index of character 'A', you can use the following expression:

     const UCHAR index = ascii_index_table['A'];

 *******************************************************************************************/
const UCHAR fontArial10_B_ascii_index_table[] = 
{
    /*      -  char     hexcode    decimal */
    /*      -  ====     =======    ======= */
     0,     /*    .        0000          0 */
     0,     /*    .        0001          1 */
     0,     /*    .        0002          2 */
     0,     /*    .        0003          3 */
     0,     /*    .        0004          4 */
     0,     /*    .        0005          5 */
     0,     /*    .        0006          6 */
     0,     /*    .        0007          7 */
     0,     /*    .        0008          8 */
     0,     /*    .        0009          9 */
     0,     /*    .        000A         10 */
     0,     /*    .        000B         11 */
     0,     /*    .        000C         12 */
     0,     /*    .        000D         13 */
     0,     /*    .        000E         14 */
     0,     /*    .        000F         15 */
     0,     /*    .        0010         16 */
     0,     /*    .        0011         17 */
     0,     /*    .        0012         18 */
     0,     /*    .        0013         19 */
     0,     /*    .        0014         20 */
     0,     /*    .        0015         21 */
     0,     /*    .        0016         22 */
     0,     /*    .        0017         23 */
     0,     /*    .        0018         24 */
     0,     /*    .        0019         25 */
     0,     /*    .        001A         26 */
     0,     /*    .        001B         27 */
     0,     /*    .        001C         28 */
     0,     /*    .        001D         29 */
     0,     /*    .        001E         30 */
     0,     /*    .        001F         31 */
     0,     /*             0020         32 */
     1,     /*    !        0021         33 */
     2,     /*    "        0022         34 */
     3,     /*    #        0023         35 */
     4,     /*    $        0024         36 */
     5,     /*    %        0025         37 */
     6,     /*    &        0026         38 */
     7,     /*    '        0027         39 */
     8,     /*    (        0028         40 */
     9,     /*    )        0029         41 */
    10,     /*    *        002A         42 */
    11,     /*    +        002B         43 */
    12,     /*    ,        002C         44 */
    13,     /*    -        002D         45 */
    14,     /*    .        002E         46 */
    15,     /*    /        002F         47 */
    16,     /*    0        0030         48 */
    17,     /*    1        0031         49 */
    18,     /*    2        0032         50 */
    19,     /*    3        0033         51 */
    20,     /*    4        0034         52 */
    21,     /*    5        0035         53 */
    22,     /*    6        0036         54 */
    23,     /*    7        0037         55 */
    24,     /*    8        0038         56 */
    25,     /*    9        0039         57 */
    26,     /*    :        003A         58 */
    27,     /*    ;        003B         59 */
    28,     /*    <        003C         60 */
    29,     /*    =        003D         61 */
    30,     /*    >        003E         62 */
    31,     /*    ?        003F         63 */
    32,     /*    @        0040         64 */
    33,     /*    A        0041         65 */
    34,     /*    B        0042         66 */
    35,     /*    C        0043         67 */
    36,     /*    D        0044         68 */
    37,     /*    E        0045         69 */
    38,     /*    F        0046         70 */
    39,     /*    G        0047         71 */
    40,     /*    H        0048         72 */
    41,     /*    I        0049         73 */
    42,     /*    J        004A         74 */
    43,     /*    K        004B         75 */
    44,     /*    L        004C         76 */
    45,     /*    M        004D         77 */
    46,     /*    N        004E         78 */
    47,     /*    O        004F         79 */
    48,     /*    P        0050         80 */
    49,     /*    Q        0051         81 */
    50,     /*    R        0052         82 */
    51,     /*    S        0053         83 */
    52,     /*    T        0054         84 */
    53,     /*    U        0055         85 */
    54,     /*    V        0056         86 */
    55,     /*    W        0057         87 */
    56,     /*    X        0058         88 */
    57,     /*    Y        0059         89 */
    58,     /*    Z        005A         90 */
    59,     /*    [        005B         91 */
    60,     /*    \        005C         92 */
    61,     /*    ]        005D         93 */
    62,     /*    ^        005E         94 */
    63,     /*    _        005F         95 */
    64,     /*    `        0060         96 */
    65,     /*    a        0061         97 */
    66,     /*    b        0062         98 */
    67,     /*    c        0063         99 */
    68,     /*    d        0064        100 */
    69,     /*    e        0065        101 */
    70,     /*    f        0066        102 */
    71,     /*    g        0067        103 */
    72,     /*    h        0068        104 */
    73,     /*    i        0069        105 */
    74,     /*    j        006A        106 */
    75,     /*    k        006B        107 */
    76,     /*    l        006C        108 */
    77,     /*    m        006D        109 */
    78,     /*    n        006E        110 */
    79,     /*    o        006F        111 */
    80,     /*    p        0070        112 */
    81,     /*    q        0071        113 */
    82,     /*    r        0072        114 */
    83,     /*    s        0073        115 */
    84,     /*    t        0074        116 */
    85,     /*    u        0075        117 */
    86,     /*    v        0076        118 */
    87,     /*    w        0077        119 */
    88,     /*    x        0078        120 */
    89,     /*    y        0079        121 */
    90,     /*    z        007A        122 */
    91,     /*    {        007B        123 */
    92,     /*    |        007C        124 */
    93,     /*    }        007D        125 */
     0,     /*    ~        007E        126 */
     0,     /*            007F        127 */
     0,     /*    ?        0080        128 */
     0,     /*    ?        0081        129 */
     0,     /*    ?        0082        130 */
     0,     /*    ?        0083        131 */
     0,     /*    ?        0084        132 */
     0,     /*    ?        0085        133 */
     0,     /*    ?        0086        134 */
     0,     /*    ?        0087        135 */
     0,     /*    ?        0088        136 */
     0,     /*    ?        0089        137 */
     0,     /*    ?        008A        138 */
     0,     /*    ?        008B        139 */
     0,     /*    ?        008C        140 */
     0,     /*    ?        008D        141 */
     0,     /*    ?        008E        142 */
     0,     /*    ?        008F        143 */
     0,     /*    ?        0090        144 */
     0,     /*    ?        0091        145 */
     0,     /*    ?        0092        146 */
     0,     /*    ?        0093        147 */
     0,     /*    ?        0094        148 */
     0,     /*    ?        0095        149 */
     0,     /*    ?        0096        150 */
     0,     /*    ?        0097        151 */
     0,     /*    ?        0098        152 */
     0,     /*    ?        0099        153 */
     0,     /*    ?        009A        154 */
     0,     /*    ?        009B        155 */
     0,     /*    ?        009C        156 */
     0,     /*    ?        009D        157 */
     0,     /*    ?        009E        158 */
     0,     /*    ?        009F        159 */
     0,     /*             00A0        160 */
     0,     /*    ?        00A1        161 */
     0,     /*    ¢        00A2        162 */
     0,     /*    £        00A3        163 */
     0,     /*    ¤        00A4        164 */
     0,     /*    ¥        00A5        165 */
     0,     /*    ¦        00A6        166 */
     0,     /*    §        00A7        167 */
     0,     /*    ¨        00A8        168 */
     0,     /*    ©        00A9        169 */
     0,     /*    ?        00AA        170 */
     0,     /*    «        00AB        171 */
     0,     /*    ¬        00AC        172 */
     0,     /*    ­        00AD        173 */
     0,     /*    ®        00AE        174 */
     0,     /*    ¯        00AF        175 */
     0,     /*    °        00B0        176 */
     0,     /*    ±        00B1        177 */
     0,     /*    ²        00B2        178 */
     0,     /*    ³        00B3        179 */
     0,     /*    ´        00B4        180 */
     0,     /*    µ        00B5        181 */
     0,     /*    ¶        00B6        182 */
     0,     /*    ·        00B7        183 */
     0,     /*    ¸        00B8        184 */
     0,     /*    ¹        00B9        185 */
     0,     /*    ?        00BA        186 */
     0,     /*    »        00BB        187 */
     0,     /*    ¼        00BC        188 */
     0,     /*    ½        00BD        189 */
     0,     /*    ¾        00BE        190 */
     0,     /*    ?        00BF        191 */
     0,     /*    A        00C0        192 */
     0,     /*    ?        00C1        193 */
     0,     /*    A        00C2        194 */
     0,     /*    ?        00C3        195 */
     0,     /*    ?        00C4        196 */
     0,     /*    ?        00C5        197 */
     0,     /*    ?        00C6        198 */
     0,     /*    C        00C7        199 */
     0,     /*    E        00C8        200 */
     0,     /*    E        00C9        201 */
     0,     /*    E        00CA        202 */
     0,     /*    E        00CB        203 */
     0,     /*    ?        00CC        204 */
     0,     /*    ?        00CD        205 */
     0,     /*    I        00CE        206 */
     0,     /*    I        00CF        207 */
     0,     /*    ?        00D0        208 */
     0,     /*    ?        00D1        209 */
     0,     /*    ?        00D2        210 */
     0,     /*    ?        00D3        211 */
     0,     /*    O        00D4        212 */
     0,     /*    ?        00D5        213 */
     0,     /*    ?        00D6        214 */
     0,     /*    ×        00D7        215 */
     0,     /*    ?        00D8        216 */
     0,     /*    U        00D9        217 */
     0,     /*    ?        00DA        218 */
     0,     /*    U        00DB        219 */
     0,     /*    U        00DC        220 */
     0,     /*    ?        00DD        221 */
     0,     /*    ?        00DE        222 */
     0,     /*    ?        00DF        223 */
     0,     /*    à        00E0        224 */
     0,     /*    ?        00E1        225 */
     0,     /*    â        00E2        226 */
     0,     /*    ?        00E3        227 */
     0,     /*    ?        00E4        228 */
     0,     /*    ?        00E5        229 */
     0,     /*    ?        00E6        230 */
     0,     /*    ç        00E7        231 */
     0,     /*    è        00E8        232 */
     0,     /*    é        00E9        233 */
     0,     /*    ê        00EA        234 */
     0,     /*    ë        00EB        235 */
     0,     /*    ?        00EC        236 */
     0,     /*    ?        00ED        237 */
     0,     /*    î        00EE        238 */
     0,     /*    ï        00EF        239 */
     0,     /*    ?        00F0        240 */
     0,     /*    ?        00F1        241 */
     0,     /*    ?        00F2        242 */
     0,     /*    ?        00F3        243 */
     0,     /*    ô        00F4        244 */
     0,     /*    ?        00F5        245 */
     0,     /*    ?        00F6        246 */
     0,     /*    ÷        00F7        247 */
     0,     /*    ?        00F8        248 */
     0,     /*    ù        00F9        249 */
     0,     /*    ?        00FA        250 */
     0,     /*    û        00FB        251 */
     0,     /*    ü        00FC        252 */
     0,     /*    ?        00FD        253 */
     0,     /*    ?        00FE        254 */
     0      /*    ?        00FF        255 */
};
#endif


#ifdef USE_EXTENDED_INDEX_TABLE
/*******************************************************************************************
  Extended index table is used to find the mapping index of a character [0-65535].

  If you can find a simple mathematical expression for index mapping, 
  you can use that, and undefine USE_EXTENDED_INDEX_TABLE.

  If you do not have such a mathematical expression, this index table is just for you.

  To get the index of character 'A', you need to calculate it like the following:

    // a sample function to get the character index on the extended index table.
    USHORT GetExtendedIndex(USHORT glpyh, const FONTHEADER_BFC *pFontHeader)
    {
        if( pFontHeader == NULL )
		      return 0; 

        USHORT firstChar = pFontHeader->firstChar;
        USHORT lastChar  = pFontHeader->lastChar;

        if( glyph < firstChar || glyph > lastChar )
			  return 0;   not found, return the first glyph index * //

        USHORT index = 0;
        GLYPH_SET *pGlyphSet = pFontHeader->extended_index_table;
        if( pGlyphSet == NULL )
			  return 0; 

        GLYPH_RANGE *pRanges = pGlyphSet->pRanges;
        if( pRanges == NULL )
		      return 0; 

        USHORT index = 0;
        USHORT nRanges = pGlyphset->nRanges;
        for(USHORT i=0; i<nRanges; i++)
        {
            USHORT charLow = pRanges[i].charLow;
            USHORT nGlyphs = pRanges[i].nGlyphs;

            if( glyph < charLow+nGlyphs )
            {
                index += (glyph - charLow); 
                return index;
            }
            else
            {
                index += nGlyphs;
            }
        }

        return 0;    not found, return the first glyph index * //

    }

 *******************************************************************************************/
const GLYPH_RANGE fontArial10_B_glyph_ranges[] = 
{
/*charLow    nGlyphs     from      to*/
/*=======    =======     =======   =======*/
  {    32,       94 }   /*[0x0020 - 0x007D]*/ 
};

const GLYPH_SET fontArial10_B_glyph_set[] = 
{
    0x10, 	/* cbThis = sizeof(GLYPH_SET) + sizeof(GLYPH_RANGE)*nRanges */
    94, 	/* nChars: total # characters in font */
    1, 		/* nRanges: # ranges */
    (GLYPH_RANGE *)fontArial10_B_glyph_ranges  /* pRanges: pointer to the first range */
};
#endif


/*******************************************************************************************
  Font Header Definition

  To use this font, you should declare it in other .h file first.
  Declare:
      1. include "bfctype.h" 
      2. extern const FONTHEADER_BFC fontArial10_B; 

 *******************************************************************************************/
const FONTHEADER_BFC fontArial10_B = 
{
    0xBFCA, 	/* magic number = 0xBFCA, created by BitFontCreator */
    0x0320, 	/* version: 0x0100 for version 1.00, 0x0210 for 2.10 */
    0x0085, 	/* font flags =  | FONT_FLAG_BW | FONT_FLAG_UNICODE */
    0, 			/* font width in pixels. 0 for variable width font */
    13, 		/* font height in pixels */
    10, 		/* font ascent (baseline) in pixels */

    0x0020, 	/* first character code defined in font */
    0x007D, 	/* last character code defined in font */
    94, 		/* # characters in font, maybe not equal to (lastchar-firstchar+1) */

    0, 			/* 1 byte reserved, not used */

    1, 			/* 1, 2, 4 bytes per unit in imagebits data table, see data length when export font data */
    0x46C, 		/* # bytes/words/dwords(based bitsPerUnit) imagebits data in data table */
    (UCHAR *)fontArial10_B_data_table, 	/*pointer to the imagebits data table*/

#ifdef USE_OFFSET_TABLE
    (ULONG *)fontArial10_B_offset_table,
#else
    NULL,
#endif

#ifdef USE_WIDTH_TABLE
    (USHORT *)fontArial10_B_width_table,
#else
    NULL,
#endif

#ifdef USE_ASCII_INDEX_TABLE
    (UCHAR *)fontArial10_B_ascii_index_table,
#else
    NULL,
#endif

#ifdef USE_EXTENDED_INDEX_TABLE
    (GLYPH_SET *)&fontArial10_B_glyph_set
#else
    NULL
#endif
};


/* clear pre-defines */

#ifdef USE_OFFSET_TABLE
#undef USE_OFFSET_TABLE
#endif

#ifdef USE_WIDTH_TABLE
#undef USE_WIDTH_TABLE
#endif

#ifdef USE_ASCII_INDEX_TABLE
#undef USE_ASCII_INDEX_TABLE
#endif

#ifdef USE_EXTENDED_INDEX_TABLE
#undef USE_EXTENDED_INDEX_TABLE
#endif

